# language: python
# python:
#   - "2.7"

notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      sudo: true
    - os: osx
      env: TARGET=x86_64-apple-darwin
      sudo: true

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/ci/build_wheel.sh
  - ls wheelhouse/

install:
  - sudo pip install pip --upgrade
  - sudo pip install --install-option="--no-cython-compile" cython
  - sudo pip install requests[security]
  - sudo pip install numpy
  - sudo pip install python-coveralls
  - sudo pip install nosexcover
  - sudo pip install -e .
cache: pip
script: nosetests -v --with-xcoverage --cover-package=convertbng --cover-tests
branches:
  only:
    - master
after_success:
  - coveralls
notifications:
  email:
    - urschrei@gmail.com
