env:
  global:
    - secure: R6T9yVugds0+ybYA8c6wsJ2gWQslOTf40oTCchictjMzv80l509YSBZCCGP0zV3Z+2NCZdsqexTzgI1USV+cPL4+nKkHUzdrvrPoCGNKEwKDDNS5Kog8AfakPzagXTM5bIEa8HGEz5i9gb9TBo+X3fT8dYqGOHMVktN4JKXmWnNfNgnBTpfchmdVpfUM/bODmcE25TM60Z7WxcTvgZIcPO8yfLIE1ltoTVLobvnwRgiWa870hOyLmkVdt4wwisUtWd7bUd1ZGix2X0EcNTVL+mBp2eBloEBcOLGlQ1TVVUaGbQkfjFBP7jA0imG6CjJOwR2M7K2LcuZeke4AuuajCNyGBDF6uDjm3FPuNrerMRT81nFnspwiaNtFNDCiise3JbG2P0w5yXfTxIOXDyGmfeWs1ACE/qdDbZTMAhxRz8YjVbv4z9AZXwtrkIKVOIiogCwApNzqeBsbditLGdYcPMcqtuYw+D++7YrDSe7tEJw8ZWWFpV5s65LAS93BUlUD6upQH3rSREDZpWRwhoJAtNdXcpWihCjPlb/RbXWvqR+IRwPBvGSRdjBfmBxvXI/NFoVM/e0lLW9ECCMLI6NYnMl2cg4VnA3EoiMfr7R2nauYOsKwogaIH5PQY/+wBTcD73XzyWUikKStUHvG13Rw6bCDW4X76GYvuon8C7d4Sn0=
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64

matrix:
  include:
    - sudo: required
      env: DOCKER_BUILD=TRUE
      services:
        - docker
    - os: osx
      osx_image: xcode7.3
      sudo: required
      env: OSX_BUILD=TRUE

before_install:
  - echo $LATEST_TAG > key.txt
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install requests[security]; fi
  - if ! [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip install requests[security]; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python ci/pre_install.py; fi
  - if ! [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo python ci/pre_install.py; fi

install:
  - bash ci/install.sh

cache: pip

script:
  - bash ci/script.sh
  - nosetests -v --with-xcoverage --cover-package=convertbng --cover-tests


branches:
  only:
    - master

after_success:
  - coveralls

notifications:
  email:
    - urschrei@gmail.com
