language: python
python:
  - "2.7"
install:
  - pip install --install-option="--no-cython-compile" cython
  - pip install numpy
  - pip install python-coveralls
  - pip install nosexcover
  - pip install -e .
cache: pip
script: nosetests -v --with-xcoverage --cover-package=convertbng --cover-tests
branches:
  only:
    - master
after_success:
  - coveralls
notifications:
  email:
    - urschrei@gmail.com
